// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkdxuzl0jq6qhLNaV-6KeksrSRzVj1ws',
    appId: '1:754007098866:web:47131e0bf880b63104976b',
    messagingSenderId: '754007098866',
    projectId: 'cycle-sun',
    authDomain: 'cycle-sun.firebaseapp.com',
    storageBucket: 'cycle-sun.appspot.com',
    measurementId: 'G-BGFWQQY0WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDLi-UruksRMyP-3Hj9sSXGUiAXitf8R0',
    appId: '1:754007098866:android:f3139c3fa272c1c904976b',
    messagingSenderId: '754007098866',
    projectId: 'cycle-sun',
    storageBucket: 'cycle-sun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBIO5KuGzxm0lR5GQoRVbtKsC8mEmhFTw',
    appId: '1:754007098866:ios:a38ad1cd91a0539e04976b',
    messagingSenderId: '754007098866',
    projectId: 'cycle-sun',
    storageBucket: 'cycle-sun.appspot.com',
    iosClientId: '754007098866-bq4see9lg26drfvq0gr7pf1a0pqepe7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.cycleSun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBIO5KuGzxm0lR5GQoRVbtKsC8mEmhFTw',
    appId: '1:754007098866:ios:a38ad1cd91a0539e04976b',
    messagingSenderId: '754007098866',
    projectId: 'cycle-sun',
    storageBucket: 'cycle-sun.appspot.com',
    iosClientId: '754007098866-bq4see9lg26drfvq0gr7pf1a0pqepe7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.cycleSun',
  );
}
